# Generated by Django 4.0 on 2022-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Unique name')),
                ('title', models.CharField(max_length=100, verbose_name='Name of site')),
                ('desc', models.TextField(verbose_name='Text for site')),
                ('img', models.ImageField(default='default.png', upload_to='site_image', verbose_name='Image')),
            ],
        ),
    ]
